
version: "3"
services:
  njs.jwtseq.service:
    build: .
    container_name: "njs.jwtseq.service"
    ports:
      - "4000:4000"
    depends_on:
      - postgresql
  postgresql:
    container_name: "postgresql"
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB: 'postgres'
      - POSTGRES_USER: 'postgres'
      - POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'